FROM python:3.7.0-slim-stretch

RUN apt-get update && \
    apt-get install -y \
    openssh-server

RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh

ADD id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

RUN mkdir /var/run/sshd
RUN chmod 0755 /var/run/sshd

RUN sed -i '/^#UseLogin/ s:.*:UseLogin yes:' /etc/ssh/sshd_config
RUN sed -i 's/\#AuthorizedKeysFile/AuthorizedKeysFile/g' /etc/ssh/sshd_config
RUN sed -i '/^PermitRootLogin/ s:.*:PermitRootLogin yes:' /etc/ssh/sshd_config

RUN rm -f /usr/bin/python && ln -s /usr/local/bin/python /usr/bin/python

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
